### PR TITLE
fix: issue #191 npm run build does not work

### LINKED ISSUE #191: `npm run build` doesn't work
1. clone the repo
2. npm ci (I didnt' use npm i, maybe this is the reason, I'm not sure)
3. npm run build

```
  10005 root@aliyun:~/treetracker-wallet-web# npm run build
  10006
  10007 > wallet-app@1.0.0 build
  10008 > GENERATE_SOURCEMAP=false react-scripts build
  10009
  10010 Creating an optimized production build...
  10011 Failed to compile.
  10012
  10013 Cannot read properties of undefined (reading 'includes')
  10014
  10015
  10016 root@aliyun:~/treetracker-wallet-web#
```

---
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by VWRoli**
The purpose of this PR is to fix #191 

The project has/had some dependency issues.

1st: Installed `react-scripts@next` first.

2nd: After that it hade problems with css
installed [PostCSS](https://github.com/postcss/postcss) and [PostCSS Normalize](https://www.npmjs.com/package/postcss-normalize)

3rd: After that, it had some problems with Babel and Eslint.
Installed `@babel/core` and `@babel/eslint-parser`.

4th: Finally had to update the parser in `.eslintrc.js`

`npm run build` works fine now.
Screenshot from 2021-12-08 09-39-14

`npm start` works as expected, and also `npm run cy` too.
`npm run cyu` has a different error now, will take a look at that, maybe I can figure it out.

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Thanks, it is fixing the `npm run build ` error. But it is giving es-lint errors.

_Ref:_ 
image

**Comment by Siddhant-K-code** [comment]
we need to add 

```js
requireConfigFile: false,
```
to fix this:


in https://github.com/Greenstand/treetracker-wallet-web/blob/5292faa754800e742bfa74b579a8b8bfcb8d913b/.eslintrc.js#L17

**Comment by VWRoli** [comment]
Updated the PR, it works now.

**Review by Siddhant-K-code — APPROVED** [review]
Finally, After [my commit - 3108251](https://github.com/VWRoli/treetracker-wallet-web/commit/31082515a883e46a08e7d8fad6ecf34f04efd0c5) and This PR, all issues related to this are fixed now.

Thanks, @VWRoli for this PR 🚀 

image

**Comment by dadiorchen** [comment]
@VWRoli @Siddhant-K-code thanks your guys effort!

**Pull request merged**
