### PR TITLE
update README

### LINKED ISSUE #79: Fix links and typos in README
**Describe the bug**
Broken image path in `README.md` and  and doc update .

**To Reproduce**
 1. Scroll to the bottom of `README.md`
 2. Click on the image with alt text `IDE VScode`
 3. You will be see 404 page since it is redirecting to image path which doesn't exist . 

**Expected behavior**
Improved `README.md` with no broken link . 

**Desktop (please complete the following information):**
 Irrelevant

### PR DESCRIPTION
**Pull request by saurabhmehta1601**
closes #79

### CODE REVIEW

**Comment by dadiorchen** [comment]
Thanks @saurabhmehta1601 ! I guess you are not in our community right? If you are interested to join our slack group, we can work together and learn, discuss some tech topic, we are a community with 600+ members.

**Comment by dadiorchen** [comment]
If you want, send me you email or leave it here (dadiorchen@outlook.com)

**Comment by saurabhmehta1601** [comment]
> saurabhmehta1601@gmail.com

**Comment by saurabhmehta1601** [comment]
> Thanks @saurabhmehta1601 ! I guess you are not in our community right? If you are interested to join our slack group, we can work together and learn, discuss some tech topic, we are a community with 600+ members.

I'll be glad to join you all

**Pull request merged**
