### PR TITLE
feat: issue #98 Make the default page desktop compatible

### LINKED ISSUE #98: Make the default page desktop compatible.
The /wallets/[wallet name] page now is working correctly on the mobile device, now need to make it compatible with the desktop screen size, the design:

Screen Shot 2021-09-08 at 11 48 15 AM

### PR DESCRIPTION
**Pull request by VWRoli**
The puprose of this PR is to fix #98 

Take a look at this @dadiorchen. Is this something what you were thinking?
Routes will be the same, we only change the components, in the 'routes' array we can add a 'DesktopComponent' if that page will have a desktop version.

As the design will be quite complex I just added some basic info for now.

My thoughts and questions: 
1. We can check for, screen size in the 'MapPage', but then we have to check screen sizes at every other route page component. So the 'App.js' is the best place for this I think. The problem right now, that I'm rendering the map in the mobile screen and the desktop screen too, separately. 

2. MapPage is a common component, it's always visible in the background, on almost every route page. I think we should render the 'MapPage' outside the Router component in the future when we will have the other routes as well. So we don't render the map on every route. 

Let me know your thoughts or if something need clarification, don't hesitate to ask.

### CODE REVIEW

**Comment by dadiorchen** [comment]
I didn't get your question, but I think current version is good, smart idea on the DesktopComponent. 
For tree page, the route: /wallets/[name]/trees/[id]
We will round MapPage (because it's /wallets/[name]) and tree page at the same time, right? We don't need to put the MapPage out of the routes list I thought?

**Comment by dadiorchen** [comment]
By the way, I was thinking for these two suites of code, we can use hook to reuse the code between these two version.

**Comment by dadiorchen** [comment]
@VWRoli what do you think?

**Comment by VWRoli** [comment]
> @VWRoli what do you think?

Sounds good to me!

**Pull request merged**
